FROM python:3-slim

ARG HOST=0.0.0.0
ARG PORT=8000
ARG TRANSPORT="http"
ARG AUTH_TYPE="none"
# Enable JWT
ARG FASTMCP_SERVER_AUTH=fastmcp.server.auth.providers.jwt.JWTVerifier
# For asymmetric verification with JWKS endpoint:
ARG FASTMCP_SERVER_AUTH_JWT_JWKS_URI="https://auth.company.com/.well-known/jwks.json"
ARG FASTMCP_SERVER_AUTH_JWT_ISSUER="https://auth.company.com"
ARG FASTMCP_SERVER_AUTH_JWT_AUDIENCE="servicenow-mcp"
ARG FASTMCP_SERVER_AUTH_JWT_REQUIRED_SCOPES="read:data,write:data"
# OR for symmetric key verification (HMAC):
ARG FASTMCP_SERVER_AUTH_JWT_PUBLIC_KEY="your-shared-secret-key-minimum-32-chars"
ARG FASTMCP_SERVER_AUTH_JWT_ALGORITHM="HS256"
ARG FASTMCP_SERVER_AUTH_JWT_ISSUER="internal-auth-service"
ARG FASTMCP_SERVER_AUTH_JWT_AUDIENCE="mcp-internal-api"
ARG TOKEN_JWKS_URI=""
ARG TOKEN_ISSUER=""
ARG TOKEN_AUDIENCE=""
ARG TOKEN_ALGORITHM=""
ARG TOKEN_SECRET=""
ARG TOKEN_PUBLIC_KEY=""
ARG REQUIRED_SCOPES=""
ARG OAUTH_UPSTREAM_AUTH_ENDPOINT=""
ARG OAUTH_UPSTREAM_TOKEN_ENDPOINT=""
ARG OAUTH_UPSTREAM_CLIENT_ID=""
ARG OAUTH_UPSTREAM_CLIENT_SECRET=""
ARG OAUTH_BASE_URL=""
ARG OIDC_CONFIG_URL=""
ARG OIDC_CLIENT_ID=""
ARG OIDC_CLIENT_SECRET=""
ARG OIDC_BASE_URL=""
ARG REMOTE_AUTH_SERVERS=""
ARG REMOTE_BASE_URL=""
ARG ALLOWED_CLIENT_REDIRECT_URIS=""
ARG EUNOMIA_TYPE="none"
ARG EUNOMIA_POLICY_FILE="mcp_policies.json"
ARG EUNOMIA_REMOTE_URL=""
ARG OPENAPI_FILE=""

ENV HOST=${HOST}
ENV PORT=${PORT}
ENV TRANSPORT=${TRANSPORT}
ENV AUTH_TYPE=${AUTH_TYPE}
ENV FASTMCP_SERVER_AUTH=${FASTMCP_SERVER_AUTH}
ENV FASTMCP_SERVER_AUTH_JWT_JWKS_URI=${FASTMCP_SERVER_AUTH_JWT_JWKS_URI}
ENV FASTMCP_SERVER_AUTH_JWT_ISSUER=${FASTMCP_SERVER_AUTH_JWT_ISSUER}
ENV FASTMCP_SERVER_AUTH_JWT_AUDIENCE=${FASTMCP_SERVER_AUTH_JWT_AUDIENCE}
ENV FASTMCP_SERVER_AUTH_JWT_REQUIRED_SCOPES=${FASTMCP_SERVER_AUTH_JWT_REQUIRED_SCOPES}
ENV FASTMCP_SERVER_AUTH_JWT_PUBLIC_KEY=${FASTMCP_SERVER_AUTH_JWT_PUBLIC_KEY}
ENV FASTMCP_SERVER_AUTH_JWT_ALGORITHM=${FASTMCP_SERVER_AUTH_JWT_ALGORITHM}
ENV FASTMCP_SERVER_AUTH_JWT_ISSUER=${FASTMCP_SERVER_AUTH_JWT_ISSUER}
ENV FASTMCP_SERVER_AUTH_JWT_AUDIENCE=${FASTMCP_SERVER_AUTH_JWT_AUDIENCE}
ENV TOKEN_JWKS_URI=${TOKEN_JWKS_URI}
ENV TOKEN_ISSUER=${TOKEN_ISSUER}
ENV TOKEN_AUDIENCE=${TOKEN_AUDIENCE}
ENV TOKEN_ALGORITHM=${TOKEN_ALGORITHM}
ENV TOKEN_SECRET=${TOKEN_SECRET}
ENV TOKEN_PUBLIC_KEY=${TOKEN_PUBLIC_KEY}
ENV REQUIRED_SCOPES=${REQUIRED_SCOPES}
ENV OAUTH_UPSTREAM_AUTH_ENDPOINT=${OAUTH_UPSTREAM_AUTH_ENDPOINT}
ENV OAUTH_UPSTREAM_TOKEN_ENDPOINT=${OAUTH_UPSTREAM_TOKEN_ENDPOINT}
ENV OAUTH_UPSTREAM_CLIENT_ID=${OAUTH_UPSTREAM_CLIENT_ID}
ENV OAUTH_UPSTREAM_CLIENT_SECRET=${OAUTH_UPSTREAM_CLIENT_SECRET}
ENV OAUTH_BASE_URL=${OAUTH_BASE_URL}
ENV OIDC_CONFIG_URL=${OIDC_CONFIG_URL}
ENV OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
ENV OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
ENV OIDC_BASE_URL=${OIDC_BASE_URL}
ENV REMOTE_AUTH_SERVERS=${REMOTE_AUTH_SERVERS}
ENV REMOTE_BASE_URL=${REMOTE_BASE_URL}
ENV ALLOWED_CLIENT_REDIRECT_URIS=${ALLOWED_CLIENT_REDIRECT_URIS}
ENV EUNOMIA_TYPE=${EUNOMIA_TYPE}
ENV EUNOMIA_POLICY_FILE=${EUNOMIA_POLICY_FILE}
ENV EUNOMIA_REMOTE_URL=${EUNOMIA_REMOTE_URL}
ENV OPENAPI_FILE=${OPENAPI_FILE}
ENV PATH="/usr/local/bin:${PATH}"
ENV UV_HTTP_TIMEOUT=3600

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
WORKDIR /app
COPY . /app

RUN pip install uv \
    && uv pip install --system --upgrade "servicenow-api[all]>=1.3.32"

CMD ["servicenow-mcp"]
ENTRYPOINT ["/entrypoint.sh"]
