name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

permissions:
  contents: read

jobs:
  publish-pages:
    uses: Knuckles-Team/pipelines/.github/workflows/pages_pipeline.yml@f304e620912e7b1e1bc1f590fa6c297faba274fb # v2.0.2
    permissions:
      contents: read
      pages: write
      id-token: write
